vich_uploader:
    db_driver: orm

    mappings:
       toto:
           uri_prefix: uploads/images/products
           upload_destination: '%kernel.project_dir%/public/images/products'
           namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
